version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      FLASK_APP: api.py

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

networks:
  catdog_network:  # Définir un réseau personnalisé nommé catdog_network
    driver: bridge  # Vous pouvez choisir le driver du réseau (bridge, overlay, etc.)
